In [41]:
#https://medium.com/swlh/linear-algebra-in-python-b967061e342a
import numpy as np
import scipy
import scipy.linalg

In [26]:
# understanding numpy array
a = np.array([[1,2,3],[4,5,6]])
a.strides
a.dtype


# slicing and indexing
b = np.array([[1,2,3,4,5,6,7,8,9,10],
             [4,5,6,7,8,9,20,11,12,13],
             [1,2,3,4,5,6,7,8,9,9]])

# what is a slice object
test = slice(1,10,2)

# basic indexing only return a "view", it will change the original array content
b0 = b[1:3,4:7]
b0[0,1] = 99
b1 = b[:,(4,7)]
b1[0,1] = 99


# understand dtype
d_type = np.dtype('<U8')
d_type.byteorder
d_type.itemsize
d_type.name

# structural array and record array
sa = np.array([('John',[88,95,100]),('Mary',[77,88,68])],
              dtype=[('student','<U8'),('grades','<i4',(3,))])
sa['student']
ra = sa.view(np.recarray)
ra.student

array(['John', 'Mary'], dtype='<U8')

In [27]:
a = np.random.randn(2,3)
a
#a.T #transpose A

array([[ 0.03538088,  0.13662954,  0.00855712],
       [-0.75789296,  0.3432679 , -1.08965008]])

In [28]:
b = np.random.randn(3,2) #
b
#b.T #transpose B

array([[-0.10133432, -0.40134174],
       [ 1.09400102,  1.17341136],
       [-0.48764524, -0.28678199]])

In [29]:
a @ b #

array([[0.14171471, 0.1436688 ],
       [0.98369868, 1.01946055]])

In [30]:
#compute rank of matrix
x = np.random.rand(2,3)
np.linalg.matrix_rank(x)

2

In [31]:
print("Independent columns vectors is number of columns\nOrthonormal vectors: Two vectors’ inner products are 0 and they are all of the unit lengths\nIf matrix A’s rows and columns are orthonormal vectors, this matrix A is an orthogonal matrix.\nit means A.T @ A = A @ A.T = I.")

Independent columns vectors is number of columns
Orthonormal vectors: Two vectors’ inner products are 0 and they are all of the unit lengths
If matrix A’s rows and columns are orthonormal vectors, this matrix A is an orthogonal matrix.
it means A.T @ A = A @ A.T = I.


In [32]:
#determinant of square matrix
x = np.random.rand(4,4)
np.linalg.det(x)

-0.10631549483230265

In [33]:
print("Gaussian Elimination can be used in: \n(a) solving a linear system Ax=b, \n(b) compute inverse matrix \n(c) solve rank \n(d) solve determinant: via a series of elementary row operations including: \n\t(1) swap rows, (2) scale rows, (3) Add one row to another.")

Gaussian Elimination can be used in: 
(a) solving a linear system Ax=b, 
(b) compute inverse matrix 
(c) solve rank 
(d) solve determinant: via a series of elementary row operations including: 
	(1) swap rows, (2) scale rows, (3) Add one row to another.


In [34]:
a = np.array([4,5,6]) 
b = np.array([7,8,9])
np.inner(a,b)
np.outer(a,b)
a * b

array([28, 40, 54])

In [35]:
print("a * b #element wise or hadamard product:\n[28, 32, 36]\n[35, 40, 45]\n[42, 48, 54]")

a * b #element wise or hadamard product:
[28, 32, 36]
[35, 40, 45]
[42, 48, 54]


In [36]:
#project one vector(a) to another(b)import requests
#https://miro.medium.com/max/852/1*Z_25fqw14MDet16ErCswYg.png
a = np.array([4,5,6])
b = np.array([7,8,9])
proj_b_a = np.inner(a,b) / np.inner(b,b) * b
proj_b_a

array([4.40206186, 5.03092784, 5.65979381])

In [37]:
print("The Gram-Schmidt process is to orthonormalize a set of vectors (v1,v2,v3…vn) to (u1,u2,u3…un) in the same Rn vector space but within which each element is of unit length and are mutually orthogonal.")

The Gram-Schmidt process is to orthonormalize a set of vectors (v1,v2,v3…vn) to (u1,u2,u3…un) in the same Rn vector space but within which each element is of unit length and are mutually orthogonal.


In [38]:
#LU decomposition.
print("LU decomposition aims to decompose a matrix (no need to be square) to a lower triangular matrix (L, entries above diagonal are 0) and an upper triangular matrix (U, entries above diagonal are 0. to make LU decomposition materialize, sometimes we reorder the matrix using a P matrix. ")

LU decomposition aims to decompose a matrix (no need to be square) to a lower triangular matrix (L, entries above diagonal are 0) and an upper triangular matrix (U, entries above diagonal are 0. to make LU decomposition materialize, sometimes we reorder the matrix using a P matrix. 


In [45]:
a = np.random.randn(3,4)
p,l,u = scipy.linalg.lu(a)
scipy.linalg.lu(a)

(array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ],
        [-0.34948116,  1.        ,  0.        ],
        [-0.26104073,  0.67929946,  1.        ]]),
 array([[-1.79236438, -1.1023231 , -0.11922257,  1.62419664],
        [ 0.        ,  0.80340273,  1.2277828 ,  1.21634248],
        [ 0.        ,  0.        , -0.42755837,  0.21483253]]))

In [53]:
print("QR decompostion aims to decompose a matrix to an orthogonal matrix (Q) and an upper triangular matrix (R). It is used in QR algorithms to solve the linear least square problem")

QR decompostion aims to decompose a matrix to an orthogonal matrix (Q) and an upper triangular matrix (R). It is used in QR algorithms to solve the linear least square problem


In [54]:
#QR decomposition.
a = np.random.randn(3,4)
q,r = np.linalg.qr(a)
np.linalg.qr(a)

(array([[-0.54574954,  0.49507357,  0.67606183],
        [ 0.00320811, -0.80556571,  0.59249776],
        [ 0.83794221,  0.32552426,  0.43804886]]),
 array([[ 2.33135625,  1.02551901,  0.59982663,  2.06929811],
        [ 0.        ,  1.23086574,  0.46167557,  0.45616345],
        [ 0.        ,  0.        , -0.27752297, -1.47310507]]))

In [55]:
#Eigen-decomposition, diagonalization, Characteristic polynomial.
#https://miro.medium.com/max/1400/1*OHOo8YKWJU_3-TelJHCiNg.png.
print("")

In [57]:
ei = np.random.randn(4,4)
w,v = np.linalg.eig(ei) #w=eigenvalues & v=eigenvector
np.linalg.eig(ei)

(array([ 1.69575282+0.j       , -0.57972954+1.0978258j,
        -0.57972954-1.0978258j, -0.17770177+0.j       ]),
 array([[ 0.20802269+0.j        ,  0.66053553+0.j        ,
          0.66053553-0.j        ,  0.68154965+0.j        ],
        [ 0.46253088+0.j        ,  0.03261016-0.10239656j,
          0.03261016+0.10239656j, -0.22607887+0.j        ],
        [ 0.83705707+0.j        , -0.01591858-0.39761075j,
         -0.01591858+0.39761075j,  0.47537856+0.j        ],
        [-0.20524916+0.j        ,  0.44367375-0.44379075j,
          0.44367375+0.44379075j,  0.50832435+0.j        ]]))

In [ ]:
#TODO: Moore-Penrose pseudo-inverse, hermitian, conjugate transpose, full-rank matrix